CLS
PRINT
COLOR 2
PRINT "     ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป"
PRINT "     บ                         ";
COLOR 30
PRINT "!!! DYNAMO GAMES !!!                       ";
COLOR 2
PRINT "บ   "; ""
PRINT "     ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ"
PRINT "     ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป"
PRINT "     บ   ";
COLOR 7
PRINT "This program is freeware so you may use it in any way you want   ";
COLOR 2
PRINT "บ"
PRINT "     ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ"
PRINT "     ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป"
PRINT "     บ ";
COLOR 7
PRINT "Dynamo Games was formed by a cross parallel universe collective    ";
COLOR 2
PRINT "บ"
PRINT "     บ ";
COLOR 7
PRINT "mind involving the minds of the Maruis de Carabas, Dr Kurt         ";
COLOR 2
PRINT "บ"
PRINT "     บ ";
COLOR 7
PRINT "Rausenstein, Albert Einstein, Branoch the Barabarian, Sir Lancelot,";
COLOR 2
PRINT "บ"
PRINT "     บ";
COLOR 7
PRINT " DJ Ultimate Peril, Julius Caesar, The Grim Reaper and a teenager   ";
COLOR 2
PRINT "บ"
PRINT "     บ ";
COLOR 7
PRINT "called David Storey.  Dynamo Games produces all sorts of games that";
COLOR 2
PRINT "บ"
PRINT "     บ ";
COLOR 7
PRINT "have been very popular throughout many other parallel universes and";
COLOR 2
PRINT "บ"
PRINT "     บ ";
COLOR 7
PRINT "will hopefully be enjoyed as much here.                            ";
COLOR 2
PRINT "บ"
PRINT "     บ   ";
COLOR 7
PRINT "DG's human representative David Storey can be e-mailed at        ";
COLOR 2
PRINT "บ"
PRINT "     บ            ";
COLOR 7
PRINT "Derek_Storey@compuserve.com                             ";
COLOR 2
PRINT "บ"
PRINT "     บ ";
COLOR 7
PRINT "or the Maruis de Carabas can sometimes be found at the GAMEDEV     ";
COLOR 2
PRINT "บ"
PRINT "     บ ";
COLOR 7
PRINT "forum.                                                             ";
COLOR 2
PRINT "บ"
PRINT "     บ   ";
COLOR 7
PRINT "Please give our programs to all your friends.  We appreciate new ";
COLOR 2
PRINT "บ"
PRINT "     บ ";
COLOR 7
PRINT "ideas and comments.  Enjoy the game!!!                             ";
COLOR 2
PRINT "บ"
PRINT "     ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ"
DO UNTIL INKEY$ <> ""
LOOP

COLOR 7
CLS
PRINT "                 *** Virtual Paint Box ***"
PRINT
INPUT "What is your message"; m$
PRINT
COLOR 1
PRINT "dark blue, ";
COLOR 2
PRINT "green, ";
COLOR 3
PRINT "green blue, ";
COLOR 4
PRINT "red, ";
COLOR 5
PRINT "purple, ";
COLOR 6
PRINT "brown, ";
COLOR 7
PRINT "white, ";
COLOR 8
PRINT "grey, ";
COLOR 9
PRINT "blue, ";
COLOR 10
PRINT "bright green, ";
COLOR 11
PRINT "light blue, "
COLOR 12
PRINT "orange, ";
COLOR 13
PRINT "pink, ";
COLOR 14
PRINT "yellow, ";
COLOR 15
PRINT "bright white."
PRINT
COLOR 7
INPUT "What colour would you like"; c$
IF c$ = "dark blue" THEN COLOR 1
IF c$ = "green" THEN COLOR 2
IF c$ = "green blue" THEN COLOR 3
IF c$ = "red" THEN COLOR 4
IF c$ = "purple" THEN COLOR 5
IF c$ = "brown" THEN COLOR 6
IF c$ = "white" THEN COLOR 7
IF c$ = "grey" THEN COLOR 8
IF c$ = "blue" THEN COLOR 9
IF c$ = "bright green" THEN COLOR 10
IF c$ = "light blue" THEN COLOR 11
IF c$ = "orange" THEN COLOR 12
IF c$ = "pink" THEN COLOR 13
IF c$ = "yellow" THEN COLOR 14
IF c$ = "bright white" THEN COLOR 15
CLS
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT "                               "; m$
COLOR 7


