CLS
PRINT "Virtual Screen..."
PRINT
1 COLOR 7
PRINT "Pardon me for being so rude it was not me it was my food."
COLOR 4
SLEEP 1
PRINT "It just came up to say hello but now it's gone back down below."
COLOR 9
SLEEP 1
PRINT "ABCDEFGHIJKLMNOPQRSTUVWXYZ >>> abcdefghijklmnopqrstuvwxyz ><><><><>"
COLOR 8
SLEEP 1
PRINT ":)  :(  :)  :(  :)  :(  :)  :(  :)  :(  :)  :(  :)  :(  :(  :)  :( :)"
COLOR 11
SLEEP 1
PRINT "This amazing screen saver was written by David Storey."
COLOR 12
SLEEP 1
PRINT "This is version 1.00   Version 2.00 will follow shortly..."
GOTO 1


