cls
print "This is the main part"
print "of the program."
end
'This is a rem line between SUBs
'This is a rem line at the end of the program.

'------------------------------------------------------------------------------
function alpha
end function

'------------------------------------------------------------------------------
function beta
print "test"
end function

'------------------------------------------------------------------------------
sub dandysub
rem dandy subroutine
end sub

'------------------------------------------------------------------------------
sub test1
rem this is a test
end sub

'------------------------------------------------------------------------------
function weirdfunction
'do nothing
'now
end function

'------------------------------------------------------------------------------
sub xray
'do nothing here too
end sub
