cls
print "This is the main part"
print "of the program."
end
sub test1
rem this is a test
end sub
function alpha
end function
sub dandysub
rem dandy subroutine
end sub
function weirdfunction
'do nothing
'now
end function
'This is a rem line between SUBs
sub xray
'do nothing here too
end sub
function beta
print "test"
end function
'This is a rem line at the end of the program.

