                          APPENDIX A

             GRAPHICS WITH ALT AND NUMERIC KEYPAD

          MYMOUSE COLORS AS PRINTED BY TANDY DMP 130A

                      COLOR MERGER TABLE







































      GRAPHICS WITH ALT AND NUMERIC KEYPAD (CHART 1 OF 2)













































      GRAPHICS WITH ALT AND NUMERIC KEYPAD (CHART 2 OF 2)









































































































































                      COLOR MERGER TABLE

The colors and their corresponding numbers:

    1 = BLUE         6 = BROWN           11 = LIGHT CYAN
    2 = GREEN        7 = LIGHT GRAY      12 = LIGHT RED
    3 = CYAN         8 = GRAY            13 = LIGHT MAGENTA
    4 = RED          9 = LIGHT BLUE      14 = YELLOW
    5 = MAGENTA     10 = LIGHT GREEN     15 = WHITE
______________________________________________________________

BACKGROUND COLORS ARE TOP ROW, LEFT TO RIGHT.
FOREGROUND COLORS ARE FIRST ROW, TOP TO BOTTOM.
Example: color 3 (cyan) on color 4 (red) results in color 7
         (light gray).

    -  0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15
    1  1  0  3  2  5  4  7  6  9  8  11  10  13  12  15  14
    2  2  3  0  1  6  7  4  5 10 11   8   9  14  15  12  13
    3  3  2  1  0  7  6  5  4 11 10   9   8  15  14  13  12
    4  4  5  6  7  0  1  2  3 12 13  14  15   8   9  10  11
    5  5  4  7  6  1  0  3  2 13 12  15  14   9   8  11  10
    6  6  7  4  5  2  3  0  1 14 15  12  13  10  11   8   9
    7  7  6  5  4  3  2  1  0 15 14  13  12  11  10   9   8
    8  8  9 10 11 12 13 14 15  0  1   2   3   4   5   6   7
    9  9  8 11 10 13 12 15 14  1  0   3   2   5   4   7   6
   10 10 11  8  9 14 15 12 13  2  3   0   1   6   7   4   5
   11 11 10  9  8 15 14 13 12  3  2   1   0   7   6   5   4
   12 12 13 14 15  8  9 10 11  4  5   6   7   0   1   2   3
   13 13 12 15 14  9  8 11 10  5  4   7   6   1   0   3   2
   14 14 15 12 13 10 11  8  9  6  7   4   5   2   3   0   1
   15 15 14 13 12 11 10  9  8  7  6   5   4   3   2   1   0

NOTE: Black (color 0) is a special case.  While black will
      function as a background color when overlaid with
      MYMOUSE tools on colors 1 through 15, you must remember
      that black cannot be used on black.  Also, black should
      never be used as a text color, and MYMOUSE has a
      built-in "block" to prevent this.