            MYMOUSE SPEED KEY QUICK REFERENCE CHART

Column A = MYMOUSE function/tool.
Column B = Speed Key to call function/tool from PLEXUS.
Column C = Speed Key(s) used in tool (with description).
* = Advanced Application (See Manual).

A                   B                C

ARCS............... A .............. L = start line / A = arcs
BIGFONT *           [Alt] [B]        [Alt] [M]
BOXES.............. B .............. -
CIRCLES             C                -
CLIP/PASTE......... [Shift] [C] .... X = corner / Y = corner
CUBES *             B                Z
DIGIFONT *......... [Alt] [D] ...... [Shift] [E] / [Alt] [M]
DRAW                D                -
ERASE.............. E .............. -
ERROR TRAP          -                -
FLIP HORIZONTAL.... F .............. H
FLIP QUARTER        F                Q
FLIP ROTATE........ F .............. R
FLIP VERTICAL       F                V
FORMAT *........... [F4] ........... -
GABLES *            A                Z
GET PICTURE........ G .............. -
GUIDELINES          L                G
KILL PICTURE....... K .............. -
LINES               L                W
MERGE.............. M .............. -
PRINTER             [Shift] [Print]  -
PRN4MAT *.......... [Alt] [P]....... On Screen / R. Button
PYRAMIDS *          B                [Shift] [Z]
QUIT PICTURE....... Q .............. -
QUIT PROGRAM        [F1]             -
SAVE PICTURE....... S .............. -
TEXT                T                -
TRIANGLES.......... A .............. L = start line/ T = triangles
WASH                W                -
ZOOM *............. [Alt] [Z]....... (On Screen) / [Alt] [M]
3D *                A                [Shift] [Z]
PAINT.............. P .............. SEE BELOW
______________________________________________________________

COLORS:  1. K Black                   9. W White
         2. E Brown                  10. Y Yellow
         3. B Blue                   11. b Light Blue
         4. G Green                  12. g Light Green
         5. C Cyan                   13. c Light Cyan
         6. R Red                    14. r Light Red
         7. M Magenta                15. m Light Magenta
         8. V Dark Gray              16. v Gray
    (For lower case letters with caps lock on use [Shift])


    PATTERNS:  [F7]   [F8]   [F9]   [F10]   [F11]   [F12]