Echo off
Echo Basic Training Tutorial
Echo -------
Echo To run the first part of the tutorial type:
Echo       BT1
Echo To run the second part of the tutorial type:
Echo       BT1
Echo There is source code for all the examples in the Basic Tutorial
Echo To get a list of the programs included, type: 
Echo       DIR *.bas
Echo .
Echo Also included are the compiled versions of several programs 
Echo that are discussed in Advanced Basic Tutorials
Echo       WINDOW
Echo       SHPSHIFT
Echo       BOUNCE
Echo .
Echo Details on these and other programs, along with source code are 
Echo included in the Advanced Basic package you receive when you register. 
Echo . 
Echo To print an order form to register the program: 
Echo       REGISTER 
Echo on 
