              
              ษอออออออออออออออออออออออออออออออออออออออออออออป
              บ ASSEMBLY LANGUAGE TOOLBOX REGISTRATION FORM บ
              ศอออออออออออออออออออออออออออออออออออออออออออออผ
                ---   ALT-QUICK v5.5x or v1.0x for VB  ---
                            by:  Christy Gemmell

 Remit To:    CPC Consulting Company                         Date: _________
 ฤฤฤฤฤฤฤฤ     1217 Crescent Drive
              Smithfield, Va. 23430
              (804) 357-9190  Voice / FAX
              (804) 357-0357 / 357-3416 / 622-8011 / Club PC BBS

þ Toolbox Registration Fee is $42.50 U.S. Dollars:                  $__42.50
þ Shipping and Handling Fees:
  ฺฟ                 ฺฟ
  ภู U.S.A.: $5.00   ภู Outside of U.S.A: $10.00                    $_______
þ Virginia Residents add 4.5% Sales Tax ($1.90):                    $_______
þ Payment Method:
  ฺฟ       ฺฟ             ฺฟ            
  ภู Check ภู Money Order ภู Postal M/O 
  ฺฟ
  ภู Company Purchase Order (#_____________)             SUB-TOTAL: $_______


þ No. of Copies (_____) X Sub-Total                          TOTAL: $_______

   ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
   บ NOTE: If payment is made by Postal Money Orders - They MUST bear the บ
   บ ฤฤฤฤ  U.S. Currency ($) symbol or  they will be returned.  I can not บ
   บ       cash out of  USA Money Orders without this marking !!  This is บ
   บ       the fastest method for payment (other than Credit Card!)       บ
   บ                                                                      บ
   บ Personal Checks are accepted but MUST be cleared prior to Shipment!  บ
   ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
               ฺฟ           ฺฟ           ฺฟ            ฺฟ      
þ Disk type:   ภู360K       ภู720K       ภู1.2M        ภู1.44M 

þ ToolBox Type:   ฺฟ           ฺฟ                  ฺฟ
                  ภูQB v4.5    ภูQBX v7.x (PDS)    ภูVB v1.0 (DOS)
þ Ship To:
           Name: ___________________________________________________________
        Company: ___________________________________________________________
       Address1: ___________________________________________________________
       Address2: ___________________________________________________________
 City,State,Zip: ___________________________________________________________
          Phone: ________________________________  [Voice]  [FAX]  [BOTH]

Any Comments?: _____________________________________________________________
               _____________________________________________________________
               _____________________________________________________________

If you are now using a Shareware Version for evaluation purposes, where was
this software obtained: ____________________________________________________
                                           
Want to DownLoad your REGISTERED copy for EXPRESS DELIVERY ?  [Yes] / [No]
If YES, What is your Club PC BBS PASSWORD ? _____________________
                                                  
                                                  
                                                  Thank-You For Registering!
                                                    CPC Consulting Company
