    DSE Software Publishing is a member of the Association of Shareware
    Professionals (ASP).  ASP wants to make sure that the shareware
    principle works for you. If you are unable to resolve a
    shareware-related problem with an ASP member by contacting the member
    directly, ASP may be able to help. The ASP Ombudsman can help you
    resolve a dispute or problem with an ASP member, but does not provide
    technical support for members' products.  Please write to the ASP
    Ombudsman at 545 Grover Road, Muskegon, MI 49442 or send a CompuServe
    message via CompuServe Mail to ASP Ombudsman 70007,3536.

