echo off
cls
echo.        To  begin  using  this  program  first  load your basic into
echo.        memory. When loading Basic leave B as  your  default  drive.
echo.        For  example,  put  the  disk  with Basic in drive A and the
echo.        program disk in drive B. From the B prompt enter. . .
echo.               A:BASICA (or GWBASIC or BASIC & press return)
echo.               After receiving the basic OK prompt enter. . .
echo.                       RUN"DOCSWAN (and press return)
echo.        You need to run the DOCSWAN program at least  once  to  read
echo.        instructions.  You  can by-pass the opening screen by typing
echo.        RUN"MENU or RUN"BTMENU.
echo. 
echo.        This disk is distributed by:   Florida PC Library
echo.                                         P.O. Box  2878
echo.                                       Leesburg, Fl 32749
echo.                                       Phone 904/787-1741
echo.        The compilation of this  disk and all  files created by the
echo.        Florida PC Library are Copyrighted 1988.
echo.
echo.        Please respect, not only our copyrighted material, but also
echo.        the  program  files  and  other files which have been copy-
echo.        righted and noted within the files by the program authors.
echo.
echo.        Programmers: We PAY for your well-written programs.
echo.
pause
cls
