     ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
     ³                                                                ³
     ³                 ASP Ombudsman Information                      ³
     ³                                                                ³
     ³  DSE Software Publishing is a member of the Association of     ³
     ³  Shareware Professionals (ASP).  ASP wants to make sure that   ³
     ³  the shareware principle works for you.  If you are unable     ³
     ³  to resolve a shareware-related problem with an ASP member     ³
     ³  by contacting the member directly, ASP may be able to help.   ³
     ³  The ASP ombudsman can help you resolve a dispute or problem   ³
     ³  with an ASP member, but does not provide technical support    ³
     ³  for members' products.  Please write to the ASP Ombudsman at: ³
     ³     ASP Ombudsman                  _______                     ³
     ³     545 Grover Road           ____|__     |                (R) ³
     ³     Muskegon, MI           --|       |    |------------------- ³
     ³        49442-9427 (USA)      |   ____|__  |  Association of    ³
     ³  or send a Compuserve        |  |       |_|  Shareware         ³
     ³  message via CompuServe      |__|   o   |    Professionals     ³
     ³  mail to 70475,1071, or    -----|   |   |--------------------- ³
     ³  a FAX to 616-788-2765.         |___|___|    MEMBER            ³
     ³                                                                ³
     ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ

