      BULLET for PowerBASIC v1.0 ORDER FORM for Credit Cards.
      (Check, cash, or money-orders use !ORDER.FRM)

     ===========================================
     | PsL ID#: 11185  Bullet for PowerBasic 3 |
     ===========================================    Qty      Extended

     BULLET, single-license  . . . . . . . $80.00 x _____ = __________
      Refer to the LICENSE AGREEMENT in CZ (under TUTORIAL_INDEX)

      Shipping/handling to all destinations for CC orders is    $6.00.
      - Next-Day Air shipment to U.S. destination, ADD $15-
      - Intl. Express Mail to Europe, ADD $20-               __________

                                                  Subtotal:  __________

             (Texas residents only, add 8.00%)   Sales tax:  __________

                                                    TOTAL: $
                                                             ==========
    *** 3.5" HD (1.44) media will be used unless you request otherwise ***
      Credit card handling is done by a service company in Houston, Texas.
      They will take your order and send it along to me. Specifically:

      You can order directly from me using the !ORDER.FRM, or for credit
      card orders you MUST order through Public (software) Library with
      your Mastercard, Visa, American Express, or Discover card. To order
      call 1-800-242-4PsL (international orders use 713-524-6394), or
      fax 713-524-6398, or by CompuServe to 71355,470. THESE NUMBERS ARE
      FOR -ORDERING- ONLY. I cannot be reached at those numbers. See the
      !README.TXT file for my BBS number and e-mail address for information
      on current prices and versions. Please DO NOT contact PsL after you
      place your order with them. Use my BBS or e-mail address, instead.

      PsL will contact me withing 24 hours of your order and I will ship
      immediately upon receiving your order from PsL. While not required,
      you are requested to mail this form soon after ordering from PsL.
      For lack of space on this form, my mailing address can instead be
      found listed in the !ORDER.FRM file.

      Contact name: ___________________________________________________

      Mailing address: ________________________________________________

      _________________________________________________________________

      _________________________________________________________________

      _________________________________________________________________

      Telephone: ____________________________  Disk size: _____________
      Special instructions or comments (continue on reverse if needed):

      Card Type:_______   Number:_____________________ Exp. Date:______

      Date: ______________   Sign:_____________________________________
      IMPORTANT:                        FORM 115-PB3-01.... 10-Oct-1994
