5 KEY(10) ON:ON KEY(10) GOSUB 600:KEY(9) ON:ON KEY(9) GOSUB 700:DIM A(15):FOR I=1 TO 15:A(I)=I:NEXT I
10 CLS:R=0:N=0:GOSUB 59980:FOR I=1 TO 100:SWAP A(INT(RND*15+1)),A(INT(RND*15+1)):NEXT I
30 LOCATE 2,34:PRINT"Analogies 6":COLOR 7,0
210 IF XX<16 THEN C=A(XX):GOTO 50
700 RUN "b:iqbuild"
5500 DATA antiseptic, bacteria, army, nation, lawyer, defense, prescription, cure, bald, hair, education, ignorance, 5, A removes B
5510 DATA aristocrat, baron, flower, stem, president, vice president, leader, follower, insect, ant, civilian, soldier, 4, an example
5520 DATA solvency, pay, poor, buy, athletic, champion, aggressive, passive, punctual, tardy, bankruptcy, profit, 2, one leads to the other
5530 DATA despotic, domineer, cordial, rebuff, timid, withdraw, aggressor, tremble, malcontent, cooperate, disgruntled, rejoice, 2, character to action
5540 DATA hold, ship, basement, house, tail, airplane, vault, security, site, edifice, garage, car, 1, part down below
5550 DATA erosion, water, bomb, fuse, wars, destruction, professional, amateur, aging, time, floor, polish, 4, action to agent
5560 DATA illness, absence, watchman, theft, trip, fall, fly, drive, award, reward, competition, defeat, 2, one follows other
5570 DATA gravel, pit, oil, well, cement, sand, tunnel, cave, crest, mountain, concrete, road, 1, up from ground
5580 DATA dam, flow, science, research, reporter, news, laws, lawyer, autocracy, liberty, education, learning, 4, A resists B
5590 DATA conjunction, clauses, guest, hospitality, bridge, shores, paragraph, sentences, walls, land, shoes, foot, 2, binds together
5600 DATA intermediatiary, arbitrate, belligerent, peace, adherent, pact, general, private, prosecutor, conviction, believer, belief, 4, his job
5610 DATA asteroid, planet, pond, lake, moon, orbit, meteor, burn, rocket, free fall, combustible, burning, 1, big to small
5620 DATA pear, potato, tomato, fruit, pint, liquid, great dane, terrier, sweet, sour, peach, turnip, 5, tree to ground
5630 DATA bear, fur, fish, seaweed, fish, gills, car, sheet metal, bug, wings, food, nutrients, 3, outside cover
5640 DATA sheep, fold, macherel, school, dog, cat, bluefish, bait, planet, solar system, tortoise, shell, 1, types of herds

5640 DATA sheep, fold, macherel, school, dog, cat, bluefish, bai