30 LOCATE 2,35:PRINT"Antonyms 2":COLOR 7,0
700 RUN "b:iqbuild"
5500 DATA able, unearned, nondescript, irregular, biased, incompetent, 5
5510 DATA reason, allegiance, safeguard, ransom, witticism, avarice, 1
5520 DATA haste, sloth, equip, frighten, help, waste, 1
5530 DATA fugitive, permanent, domestic, affirmative, eligible, mortal, 1
5540 DATA nonchalant, mendable, peculiar, sneering, excitable, boring, 4
5550 DATA dread, plea, weakness, shriek, welcome, revise, 4
5560 DATA humorous, avaricious, solemn, ambiguous, farcical, structural, 2
5570 DATA charge, absolve, bless, breach, purchase, cancel, 1
5580 DATA abrasive, victorious, suitable, uninhabited, smooth, damp, 4
5590 DATA exalt, abase, submit, laud, issue, bury, 1
5600 DATA frank, uncommon, restrained, eloquent, undefined, indolent, 2
5610 DATA brazen, cultivated, broken, shy, tough, burnish, 3
5620 DATA censure, becalm, offset, praise, besiege, profit, 3
5630 DATA humility, pride, redundancy, meanness, solitude, dryness, 1
5640 DATA formidable, mortal, unreasonable, confused, pleasant, shapely, 4
5650 DATA blame, misrepresent, recourse, absolve, defy, match, 3
5660 DATA defer, accelerate, embroil, blunder, reinstate, escape, 1
5670 DATA eccentric, disinterested, objective, oblique, trustworthy, ordinary, 5
5680 DATA feasible, conventional, impractical, unclean, fearful, mundane, 2
5690 DATA casual, belated, idyllic, deliberate, decorous, benevolent, 3
5700 DATA prosperity, adversity, uncertainty, democracy, renown, avocation, 1
5710 DATA lunacy, rectitude, chicanery, sanity, deliverance, cleverness, 3
5720 DATA chide, jest, belabor, huddle, praise, devour, 4
5730 DATA intentional, pronounced, accidental, continual, auxiliary, rotund, 2
5740 DATA earnest, laconic, tranquil, legendary, frivolous, irrelevant, 4
5750 DATA dally, relax, hasten, declaim, prevail, rebel, 2
5760 DATA foster, unfrock, recondition, discharge, discourage, upstage, 4
5770 DATA lofty, doctrinaire, mechanical, lowly, marginal, civil, 3
5780 DATA ethical, dogmatic, artistic, immoral, political, learned, 3
5790 DATA dowdy, contrived, emphatic, young, twisted, chic, 5
5800 DATA genial, vulnerable, uneven, sullen, nimble, hungry, 3
5810 DATA wearisome, knowing, agreeable, fiery, interesting, gentle, 4
5820 DATA explicit, immodest, conceited, valid, ambiguous, improbable, 4
5830 DATA denounce, commend, rebut, behold, dissemble, establish, 1
5840 DATA abet, compress, install, polarize, hinder, uncover, 4
TA denounce, commend, rebut, behold, dissemble, esta