5 CLS:KEY OFF:SCREEN 0,0,0:WIDTH 80:CLEAR:FOR I=1 TO 10:KEY I,"":NEXT:KEY 2,"GOTO 60"+CHR$(13):KEY 10,"RUN"+CHR$(34)+"BLUEMENU"+CHR$(34)+CHR$(13):LIST 10-57
12 '*****************   PUT TITLE HERE #############  *************************
16 'ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
18 'บ                                                                         บ
20 'บ                                                                         บ
22 'บ                                                                         บ
24 'บ                                                                         บ
26 'บ                                                                         บ
28 'บ                                                                         บ
30 'บ                                                                         บ
32 'บ                                                                         บ
34 'บ                                                                         บ
36 'บ                                                       Ver 5.2/160/320   บ
50 'ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
54 '        *****  < F2 > to RUN  *******  < F10 > For BLUEMENU  *****
55 ' ====== To avoid DOCUMENTATION BOX each time, REM or DELETE  line 5 ======
56 '**** ADD THE WORDS YOU WANT IN THE BOX AND DELETE EXTRA LINES TO BRING ****
57 '*** THE BOX DOWN TO SIZE.   SAVE THIS WITH THE "A" OPTION TO RUN "MERGE" **
58 '** START YOUR PROGRAM NUMBERING AT 100 FOR MERGE PURPOSES. RENUMBER LATER.*
60 CLS:SCREEN 0,0,0:WIDTH 80:CLEAR:FOR I=1 TO 10:KEY I,"":NEXT
100 GOTO 5
64900 END
65000 '************************* SAVE ROUTINE ********************************
65100 SAVE"B:PROGHEAD.BAS",A
TO 5
64900 END
65000 '************************* SAVE ROUTINE ********************************
65100 SAVE"B:PROGHE