CLS
@echo off
echo                     ษออออออออออออออออออออออออออออออออออป
echo                     บ A.L. Interactive Install Program บ
echo                     บ ๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎ บ
echo                     ศออออออออออออออออออออออออออออออออออผ
echo                     ษออออออออออออออออออออออออออออออออออป
echo                     บ    Please wait.....Installing    บ
echo                     ศออออออออออออออออออออออออออออออออออผ
@echo off
MD c:\STARZ~1
MOVE C:\CSERVE\DOWNLOAD\STRZGAZE.BAS C:\STARZG~1
MOVE C:\CSERVE\DOWNLOAD\SGSPD.STG C:\STARZG~1
MOVE C:\CSERVE\DOWNLOAD\SGHIGH.STG C:\STARZG~1
MOVE C:\CSERVE\DOWNLOAD\SGABOUT.TXT C:\STARZG~1
MOVE C:\CSERVE\DOWNLOAD\SGINST.TXT C:\STARZG~1
echo                     ------------------------------------
echo                       The software has been succesfully
echo                       installed into C:\StarzGaze
echo                     ------------------------------------
echo                          Thankyou and and have fun!




