10 REM 19:04:16  2/24/1985
20 CLS
30 FOR I =1 TO 33
60 LOCATE 5,I:PRINT" A BASIC TUTORIAL";
70 FOR D =1 TO 10 :NEXT D
80 NEXT I
90 PRINT TAB(38);"FOR THE"
100 PRINT TAB(33);"LANGUAGE OF BASIC
110 PRINT:PRINT:PRINT
120 FOR A =1 TO 39
130 PRINT "<>";
140 NEXT A
150 PRINT:PRINT:PRINT:PRINT
160 PRINT "                          A SELF-PACED LEARNING PROGRAM
170 PRINT
180 PRINT "                               by  Mark A. Swanson
190 PRINT "
200 PRINT
210 PRINT:PRINT:PRINT
220 PRINT "************************  DOC SWAN Learning Series (sm)  *********************"
230 FOR I=1 TO 2000 :NEXT I
240 CLS
250 PRINT "WELCOME !!!
260 PRINT 
270 PRINT "         You have just openned the door to hours of fun, creativity,
280 PRINT "         and productivity by choosing to learn the powerfull BASIC
290 PRINT "         computer language.
300 PRINT
310 PRINT "         Many people are intimidated by new languages and so is the 
320 PRINT "         case with computer languages.  What they don't realize is
330 PRINT "         that BASIC is designed to be just that - basic.
340 PRINT
350 PRINT "         You'll find that using BASIC is even more straight forward
360 PRINT "         than the English we use every day.  You'll use simple words
370 PRINT "         with which to tell the computer what you want it to do.
380 PRINT
390 PRINT "         When you have finished this 'mini-course', and have a few
400 PRINT "         hours of practice under your belt, you'll be programming
410 PRINT "         up a storm.  Here are a few tips to help the learning process..."
420 PRINT
430 PRINT "         1.  Read each section carefully to insure comprehension.
440 PRINT "         2.  Practice after each session.
450 PRINT "         3.  Relax, take your time, and ENJOY !
460 PRINT:PRINT
470 INPUT  "          PRESS THE  [RETURN]  KEY FOR THE TUTORIAL MAIN MENU ",Z$
480 LOAD"B:BTMENU.BAS",R
 !
460 PRINT:PRINT
470 INPUT  "          PRESS THE  [RETURN]  KEY FOR THE TUTORIAL MAIN MENU ",Z$
480 LOAD"B:BTMENU.BA